In [1]:
import pandas as pd
import glob
import os

output_file = "./data/clean_aqi_2020_2024.csv"

# 如果文件已存在就删除，避免重复写入
if os.path.exists(output_file):
    os.remove(output_file)

all_files = glob.glob(r"D:\Downloads\FYP CHINA\data\百度\*_*/*/*.csv", recursive=True)

for file in all_files:
    print(f"📥 处理文件: {file}")
    try:
        # 读取文件，只保留必要列
        df = pd.read_csv(file, encoding="utf-8")

        non_city_cols = ["date", "hour", "type", "Unnamed: 0"]
        city_cols = [col for col in df.columns if col not in non_city_cols]

        # 只处理重要污染物类型（减少内存）
        df = df[df["type"].isin(["AQI", "PM2.5", "PM10", "SO2", "NO2", "CO", "O3"])]

        # 转长表
        df_long = df.melt(id_vars=["date", "hour", "type"], value_vars=city_cols,
                          var_name="city", value_name="value")

        # 转宽表
        df_pivot = df_long.pivot_table(
            index=["date", "hour", "city"],
            columns="type",
            values="value",
            aggfunc='mean'   # 防止重复数据
        ).reset_index()

        df_pivot.columns.name = None

        # 转换日期
        df_pivot["date"] = pd.to_datetime(df_pivot["date"], format="%Y%m%d", errors="coerce")

        # 写入文件（逐步 append）
        df_pivot.to_csv(output_file, mode='a', index=False, header=not os.path.exists(output_file), encoding="utf-8")

        print(f"✔ 处理成功: {file}")

    except Exception as e:
        print(f"❌ 处理失败: {file}, 错误: {e}")

print("\n🎉 完成！数据已保存到：", output_file)

📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200101.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200101.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200102.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200102.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200103.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200103.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200104.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200104.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200105.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200105.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200106.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200106.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200107.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200107.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200108.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200108.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200109.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200109.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200110.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200110.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200111.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200111.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200112.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200112.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200113.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200113.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200114.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200114.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200115.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200115.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200116.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200116.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200117.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200117.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200118.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200118.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200119.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200119.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200120.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200120.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200121.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200121.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200122.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200122.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200123.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200123.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200124.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200124.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200125.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200125.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200126.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200126.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200127.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200127.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200128.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200128.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200129.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200129.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200130.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200130.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200131.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200131.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200201.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200201.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200202.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200202.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200203.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200203.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200204.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200204.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200205.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200205.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200206.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200206.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200207.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200207.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200208.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200208.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200209.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200209.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200210.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200210.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200211.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200211.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200212.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200212.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200213.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200213.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200214.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200214.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200215.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200215.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200216.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200216.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200217.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200217.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200218.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200218.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200219.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200219.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200220.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200220.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200221.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200221.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200222.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200222.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200223.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200223.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200224.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200224.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200225.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200225.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200226.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200226.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200227.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200227.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200228.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200228.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200229.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200229.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200301.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200301.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200302.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200302.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200303.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200303.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200304.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200304.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200305.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200305.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200306.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200306.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200307.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200307.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200308.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200308.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200309.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200309.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200310.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200310.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200311.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200311.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200312.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200312.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200313.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200313.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200314.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200314.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200315.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200315.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200316.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200316.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200317.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200317.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200318.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200318.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200319.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200319.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200320.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200320.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200321.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200321.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200322.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200322.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200323.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200323.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200324.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200324.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200325.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200325.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200326.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200326.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200327.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200327.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200328.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200328.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200329.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200329.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200330.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200330.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200331.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200331.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200401.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200401.csv
📥 处理文件: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200402.csv
✔ 处理成功: D:\Downloads\FYP CHINA\data\百度\城市_20200101-20201231\城市_20200101-20201231\china_cities_20200402.csv

In [2]:
import pandas as pd

df = pd.read_csv("./data/clean_aqi_2020_2024.csv", encoding="utf-8")

df.head(5)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98515780 entries, 0 to 98515779
Data columns (total 10 columns):
 #   Column  Dtype
---  ------  -----
 0   date    object
 1   hour    int64
 2   city    object
 3   AQI     float64
 4   CO      float64
 5   NO2     float64
 6   O3      float64
 7   PM10    float64
 8   PM2.5   float64
 9   SO2     float64
dtypes: float64(7), int64(1), object(2)
memory usage: 7.3+ GB

,hour,AQI,CO,NO2,O3,PM10,PM2.5,SO2
count,9.851578e+07,9.545182e+07,9.744493e+07,9.762193e+07,9.737487e+07,9.607992e+07,9.720922e+07,9.775506e+07
mean,1.150405e+01,5.681929e+01,6.634498e-01,2.311004e+01,6.557759e+01,5.976619e+01,3.205331e+01,8.687394e+00
std,6.926604e+00,4.518053e+01,3.852741e-01,1.845965e+01,4.192423e+01,7.904858e+01,4.045115e+01,8.665234e+00
min,0.000000e+00,0.000000e+00,1.000000e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,5.000000e+00,3.000000e+01,4.000000e-01,1.000000e+01,3.400000e+01,2.600000e+01,1.300000e+01,5.000000e+00
50%,1.200000e+01,4.700000e+01,6.000000e-01,1.800000e+01,6.000000e+01,4.400000e+01,2.300000e+01,7.000000e+00
75%,1.800000e+01,6.800000e+01,8.000000e-01,3.000000e+01,9.000000e+01,7.300000e+01,4.000000e+01,1.000000e+01
max,2.300000e+01,5.000000e+02,9.000000e+01,1.028000e+03,1.200000e+03,1.000000e+05,2.000000e+05,1.575000e+03

In [6]:
import pandas as pd
import os

df_all = pd.read_csv("./data/clean_aqi_2020_2024.csv", encoding="utf-8")

cities = df_all["city"].unique()

# 创建输出文件夹（重要！！）
os.makedirs("data/cities", exist_ok=True)

for city in cities:
    df_city = df_all[df_all["city"] == city]

    output_path = f"data/cities/{city}.csv"

    header = not os.path.exists(output_path)
    df_city.to_csv(output_path, mode="a", index=False, header=header)

print("🎉 拆分完成！每个城市已经有单独的 CSV 文件。")

KeyboardInterrupt:

In [3]:
import os
import pandas as pd

# 你的城市文件夹路径
folder = r"D:\Downloads\FYP CHINA\data\cities"

# 读取所有文件名
files = os.listdir(folder)

# 只保留 .csv 文件（或你实际的扩展名）
city_files = [f for f in files if f.lower().endswith(".csv")]

# 提取城市名称（去掉 .csv）
cities = [os.path.splitext(f)[0] for f in city_files]

print("总城市文件数 =", len(cities))
print(cities)

# 检查中文文件名（排除英文与数字）
non_chinese = [c for c in cities if not all('\u4e00' <= ch <= '\u9fff' for ch in c)]

if non_chinese:
    print("\n⚠️ 存在非中文名称文件：")
    for c in non_chinese:
        print(" -", c)
else:
    print("\n所有文件名都是中文城市名 ✓")

# 保存城市列表到 CSV（可选）
df = pd.DataFrame({"city": cities})
df.to_csv("cities_list.csv", index=False, encoding="utf-8-sig")
print("\n城市列表已另存为 cities_list.csv")

总城市文件数 = 391
['七台河', '三亚', '三明', '三沙', '三门峡', '上海', '上饶', '东莞', '东营', '中卫', '中山', '临夏回族自治州', '临夏州', '临安', '临汾', '临沂', '临沧', '丹东', '丽水', '丽江', '义乌', '乌兰察布', '乌海', '乌鲁木齐', '乐山', '九江', '乳山', '云浮', '五家渠', '亳州', '伊春', '伊犁哈萨克州', '佛山', '佳木斯', '保定', '保山', '信阳', '儋州', '克孜勒苏柯尔克孜自治州', '克州', '克拉玛依', '六安', '六盘水', '兰州', '兰州新区', '兴安盟', '内江', '凉山州', '凉山彝族自治州', '包头', '北京', '北海', '十堰', '南京', '南充', '南宁', '南平', '南昌', '南通', '南阳', '博尔塔拉蒙古自治州', '博州', '即墨', '厦门', '双鸭山', '句容', '台州', '合肥', '吉安', '吉林', '吐鲁番地区', '吕梁', '吴忠', '吴江', '周口', '呼伦贝尔', '呼和浩特', '和田地区', '咸宁', '咸阳', '哈密地区', '哈尔滨', '唐山', '商丘', '商洛', '喀什地区', '嘉兴', '嘉峪关', '四平', '固原', '塔城地区', '大兴安岭地区', '大同', '大庆', '大理州', '大连', '天水', '天津', '太仓', '太原', '威海', '娄底', '孝感', '宁德', '宁波', '安庆', '安康', '安阳', '安顺', '定西', '宜兴', '宜宾', '宜昌', '宜春', '宝鸡', '宣城', '宿州', '宿迁', '富阳', '寿光', '山南', '岳阳', '崇左', '巴中', '巴彦淖尔', '巴音郭楞州', '常州', '常德', '常熟', '平凉', '平度', '平顶山', '广元', '广安', '广州', '庆阳', '库尔勒', '廊坊', '延安', '延边州', '延边朝鲜族自治州', '开封', '张家口', '张家港', '张家界', '张掖', '徐州', '德宏州', '德州', '德阳', '忻州', '怀化', '怒江州', '恩施土家族苗族自治州', '恩施州', '惠州', '成都', '扬州', '承德', '抚州', '抚顺', '拉萨', '招远', '揭阳', '攀枝花', '文山州', '文登', '新乡', '新余', '无锡', '日喀则', '日照', '昆山', '昆明', '昌吉州', '昌都', '昭通', '晋中', '晋城', '普洱', '景德镇', '曲靖', '朔州', '朝阳', '本溪', '来宾', '杭州', '松原', '林芝', '果洛州', '果洛藏族自治州', '枣庄', '柳州', '株洲', '桂林', '梅州', '梧州', '楚雄州', '榆林', '武威', '武汉', '毕节', '永州', '汉中', '汕头', '汕尾', '江门', '江阴', '池州', '沈阳', '沧州', '河池', '河源', '泉州', '泰安', '泰州', '泸州', '洛阳', '济南', '济宁', '海东地区', '海北州', '海北藏族自治州', '海南州', '海南藏族自治州', '海口', '海西州', '海西蒙古族藏族自治州', '海门', '淄博', '淮北', '淮南', '淮安', '深圳', '清远', '温州', '渭南', '湖州', '湘潭', '湘西州', '湛江', '溧阳', '滁州', '滨州', '漯河', '漳州', '潍坊', '潮州', '濮阳', '烟台', '焦作', '牡丹江', '玉林', '玉树州', '玉树藏族自治州', '玉溪', '珠海', '瓦房店', '甘南州', '甘孜州', '甘孜藏族自治州', '白城', '白山', '白银', '百色', '益阳', '盐城', '盘锦', '眉山', '石嘴山', '石家庄', '石河子', '福州', '秦皇岛', '章丘', '红河州', '绍兴', '绥化', '绵阳', '聊城', '肇庆', '胶南', '胶州', '自贡', '舟山', '芜湖', '苏州', '茂名', '荆州', '荆门', '荣成', '莆田', '莱州', '莱西', '菏泽', '萍乡', '营口', '葫芦岛', '蓬莱', '蚌埠', '衡水', '衡阳', '衢州', '襄阳', '西双版纳州', '西咸新区', '西宁', '西安', '许昌', '诸暨', '贵港', '贵阳', '贺州', '资阳', '赣州', '赣江新区', '赤峰', '辽源', '辽阳', '达州', '运城', '连云港', '迪庆州', '通化', '通辽', '遂宁', '遵义', '邢台', '那曲', '那曲地区', '邯郸', '邵阳', '郑州', '郴州', '鄂尔多斯', '鄂州', '酒泉', '重庆', '金华', '金坛', '金昌', '钦州', '铁岭', '铜仁地区', '铜川', '铜陵', '银川', '锡林郭勒盟', '锦州', '镇江', '长春', '长沙', '长治', '阜新', '阜阳', '防城港', '阳江', '阳泉', '阿克苏地区', '阿勒泰地区', '阿坝州', '阿坝藏族羌族自治州', '阿拉善盟', '阿里地区', '陇南', '随州', '雄安新区', '雅安', '青岛', '鞍山', '韶关', '马鞍山', '驻马店', '鸡西', '鹤壁', '鹤岗', '鹰潭', '黄冈', '黄南州', '黄南藏族自治州', '黄山', '黄石', '黑河', '黔东南州', '黔东南苗族侗族自治州', '黔南州', '黔南布依族苗族自治州', '黔西南州', '黔西南布依族苗族自治州', '齐齐哈尔', '龙岩']

所有文件名都是中文城市名 ✓

城市列表已另存为 cities_list.csv

In [4]:
# data_clean_pipeline.py
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import chardet
import warnings
warnings.filterwarnings("ignore")

# --------------- 配置区（可按需修改） ----------------
SRC_FOLDER = r"D:\Downloads\FYP CHINA\data\cities"
OUT_FOLDER = r"D:\Downloads\FYP CHINA\data\cleaned_cities"
MASTER_OUT = r"D:\Downloads\FYP CHINA\data\cleaned_all_cities.csv"
SUMMARY_OUT = r"D:\Downloads\FYP CHINA\data\clean_summary.csv"

# 插值策略与阈值
INTERP_METHOD = "linear"
MAX_GAP_HOURS = 168   # 若连续缺失超过多少小时仍不插补（可视需要调整）
# 合理物理阈值（超出设为 NaN）
THRESHOLDS = {
    "AQI": (0, 1000),
    "PM2.5": (0, 5000),
    "PM10": (0, 10000),
    "NO2": (0, 5000),
    "SO2": (0, 5000),
    "O3": (0, 5000),
    "CO": (0, 100)   # 单位 mg/m3 可能不一样，谨慎
}
# -----------------------------------------------------

os.makedirs(OUT_FOLDER, exist_ok=True)
# 如果 master 已存在，先删除（重建）
if os.path.exists(MASTER_OUT):
    os.remove(MASTER_OUT)

def detect_encoding(file_path, n_bytes=20000):
    # 试探性探测编码
    with open(file_path, "rb") as f:
        raw = f.read(n_bytes)
    res = chardet.detect(raw)
    return res["encoding"] if res["encoding"] else "utf-8"

def unify_columns(df):
    # 将常见变体统一到目标字段名
    col_map = {}
    for c in df.columns:
        c0 = str(c).strip().lower()
        if c0 in ["date", "日期", "day"]:
            col_map[c] = "date"
        elif c0 in ["hour","小时","时"]:
            col_map[c] = "hour"
        elif "aqi" in c0:
            col_map[c] = "AQI"
        elif c0.replace(".","").replace("-","").replace("_","") in ["pm25","pm2.5","pm_25","pm2_5"]:
            col_map[c] = "PM2.5"
        elif "pm10" in c0:
            col_map[c] = "PM10"
        elif "so2" in c0:
            col_map[c] = "SO2"
        elif "no2" in c0:
            col_map[c] = "NO2"
        elif "o3" in c0:
            col_map[c] = "O3"
        elif "co" == c0 or c0.startswith("co "):
            col_map[c] = "CO"
        else:
            # 其余保留原名
            col_map[c] = c
    df = df.rename(columns=col_map)
    return df

def numeric_safe(series):
    return pd.to_numeric(series, errors="coerce")

def apply_thresholds(df):
    for col, (low, high) in THRESHOLDS.items():
        if col in df.columns:
            df.loc[(df[col] < low) | (df[col] > high), col] = np.nan
    return df

def process_city_file(file_path, city_name):
    # 1. 自动检测编码并读取
    try:
        enc = detect_encoding(file_path)
        df = pd.read_csv(file_path, encoding=enc)
    except Exception as e:
        # fallback
        df = pd.read_csv(file_path, encoding="utf-8", errors="replace")
    # 2. 统一列名
    df = unify_columns(df)
    # 3. ensure required columns exist
    # Some files may already be in cleaned format; handle common cases
    # If file already contains 'datetime' and pollutants, use it
    if "datetime" in df.columns:
        df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    else:
        # require date & hour columns
        if "date" not in df.columns:
            # try to infer from filename (if date embedded) or return empty
            df["date"] = np.nan
        if "hour" not in df.columns:
            # maybe it's daily file; assume hour=0
            df["hour"] = 0
        # normalize date strings (try various parse)
        df["date"] = df["date"].astype(str).str.strip()
        # convert date-like numeric YYYYMMDD -> YYYY-MM-DD
        df.loc[df["date"].str.match(r"^\d{8}$", na=False), "date"] = \
            pd.to_datetime(df.loc[df["date"].str.match(r"^\d{8}$", na=False), "date"], format="%Y%m%d").dt.strftime("%Y-%m-%d")
        # parse to datetime
        df["hour"] = df["hour"].fillna(0).astype(int)
        # combine
        df["datetime"] = pd.to_datetime(df["date"], errors="coerce") + pd.to_timedelta(df["hour"], unit="h")
    # Drop rows without datetime
    df = df.dropna(subset=["datetime"])
    # 4. keep only columns we care about
    keep_cols = ["datetime", "AQI", "PM2.5", "PM10", "SO2", "NO2", "CO", "O3"]
    # convert numeric where present
    for c in keep_cols:
        if c in df.columns:
            df[c] = numeric_safe(df[c])
        else:
            df[c] = np.nan
    # 5. groupby datetime (in case duplicates) and aggregate mean
    df = df.groupby("datetime", as_index=False)[keep_cols[1:]].mean()
    # 6. reindex to full hourly range
    start = df["datetime"].min()
    end = df["datetime"].max()
    if pd.isna(start) or pd.isna(end):
        return None, {"city": city_name, "rows_before":0, "rows_after":0, "missing_after":0}
    full_idx = pd.date_range(start=start.floor('H'), end=end.ceil('H'), freq="H")
    df = df.set_index(pd.DatetimeIndex(df["datetime"])).reindex(full_idx)
    df.index.name = "datetime"
    df = df.drop(columns=["datetime"], errors="ignore")
    # 7. mark city column
    df["city"] = city_name
    # 8. apply thresholds (outliers -> NaN)
    df = apply_thresholds(df.reset_index())
    # 9. count missing before interp
    missing_before = df[["AQI","PM2.5","PM10","SO2","NO2","CO","O3"]].isna().sum().to_dict()
    # 10. Interpolate per column with limit for large gaps
    # use time interpolation (index is datetime)
    df = df.set_index("datetime")
    # limit: do not fill gaps larger than MAX_GAP_HOURS
    # create a helper mask to avoid interpolating over very long gaps
    # We'll do simple linear interpolation with limit = MAX_GAP_HOURS
    df_interp = df.copy()
    for col in ["AQI","PM2.5","PM10","SO2","NO2","CO","O3"]:
        if col in df_interp.columns:
            df_interp[col] = df_interp[col].interpolate(method="time", limit=MAX_GAP_HOURS, limit_direction="both")
    # 11. After interp, forward/backward fill small edges
    df_interp = df_interp.fillna(method="ffill").fillna(method="bfill")
    # 12. Round numeric columns reasonably
    for col in ["AQI","PM2.5","PM10","SO2","NO2","CO","O3"]:
        if col in df_interp.columns:
            df_interp[col] = df_interp[col].round(3)
    # 13. statistics
    rows_before = len(df)
    rows_after = len(df_interp)
    missing_after = df_interp.isna().sum().to_dict()
    # 14. reset index
    df_out = df_interp.reset_index()
    # 15. reorder columns
    cols_order = ["datetime","city","AQI","PM2.5","PM10","SO2","NO2","CO","O3"]
    df_out = df_out[cols_order]
    return df_out, {"city": city_name, "rows_before":rows_before, "rows_after":rows_after, "missing_before":missing_before, "missing_after":missing_after}

# ---------------- 批处理主流程 ----------------
city_files = [f for f in os.listdir(SRC_FOLDER) if f.lower().endswith(".csv")]
summary_list = []

for fname in tqdm(city_files, desc="Cities"):
    city = os.path.splitext(fname)[0]
    fpath = os.path.join(SRC_FOLDER, fname)
    try:
        df_city_clean, stats = process_city_file(fpath, city)
        if df_city_clean is None:
            print(f"⚠️ {city}: 处理后为空，跳过")
            continue
        # 保存 per-city clean file
        out_path = os.path.join(OUT_FOLDER, f"{city}.csv")
        df_city_clean.to_csv(out_path, index=False, encoding="utf-8")
        # append to master CSV (streaming)
        header = not os.path.exists(MASTER_OUT)
        df_city_clean.to_csv(MASTER_OUT, mode="a", index=False, header=header, encoding="utf-8")
        # add to summary
        stats_row = {
            "city": city,
            "rows_out": stats["rows_after"],
            "missing_after_AQI": stats["missing_after"].get("AQI", np.nan),
            "missing_after_PM2.5": stats["missing_after"].get("PM2.5", np.nan),
            "missing_after_PM10": stats["missing_after"].get("PM10", np.nan),
        }
        summary_list.append(stats_row)
    except Exception as e:
        print(f"❌ 处理失败: {city} -> {e}")

# 保存summary
df_summary = pd.DataFrame(summary_list)
df_summary.to_csv(SUMMARY_OUT, index=False, encoding="utf-8-sig")
print("全部完成。cleaned files at:", OUT_FOLDER)
print("master file:", MASTER_OUT)
print("summary:", SUMMARY_OUT)

Cities:   1%|          | 2/391 [00:00<00:50,  7.65it/s]

❌ 处理失败: 七台河 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 三亚 -> 'numpy.int64' object has no attribute 'floor'

Cities:   1%|▏         | 5/391 [00:00<00:39,  9.89it/s]

❌ 处理失败: 三明 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 三沙 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 三门峡 -> 'numpy.int64' object has no attribute 'floor'

Cities:   2%|▏         | 7/391 [00:00<00:45,  8.44it/s]

❌ 处理失败: 上海 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 上饶 -> 'numpy.int64' object has no attribute 'floor'

Cities:   2%|▏         | 9/391 [00:01<00:46,  8.20it/s]

❌ 处理失败: 东莞 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 东营 -> 'numpy.int64' object has no attribute 'floor'

Cities:   3%|▎         | 11/391 [00:01<00:48,  7.88it/s]

❌ 处理失败: 中卫 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 中山 -> 'numpy.int64' object has no attribute 'floor'

Cities:   4%|▎         | 14/391 [00:01<00:35, 10.51it/s]

❌ 处理失败: 临夏回族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 临夏州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 临安 -> 'numpy.int64' object has no attribute 'floor'

Cities:   4%|▍         | 16/391 [00:01<00:41,  9.00it/s]

❌ 处理失败: 临汾 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 临沂 -> 'numpy.int64' object has no attribute 'floor'

Cities:   5%|▍         | 18/391 [00:02<00:45,  8.27it/s]

❌ 处理失败: 临沧 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 丹东 -> 'numpy.int64' object has no attribute 'floor'

Cities:   5%|▌         | 20/391 [00:02<00:46,  7.93it/s]

❌ 处理失败: 丽水 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 丽江 -> 'numpy.int64' object has no attribute 'floor'

Cities:   6%|▌         | 22/391 [00:02<00:42,  8.69it/s]

❌ 处理失败: 义乌 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 乌兰察布 -> 'numpy.int64' object has no attribute 'floor'

Cities:   6%|▌         | 24/391 [00:02<00:44,  8.21it/s]

❌ 处理失败: 乌海 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 乌鲁木齐 -> 'numpy.int64' object has no attribute 'floor'

Cities:   7%|▋         | 26/391 [00:03<00:44,  8.21it/s]

❌ 处理失败: 乐山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 九江 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 乳山 -> 'numpy.int64' object has no attribute 'floor'

Cities:   7%|▋         | 29/391 [00:03<00:41,  8.69it/s]

❌ 处理失败: 云浮 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 五家渠 -> 'numpy.int64' object has no attribute 'floor'

Cities:   8%|▊         | 31/391 [00:03<00:43,  8.28it/s]

❌ 处理失败: 亳州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 伊春 -> 'numpy.int64' object has no attribute 'floor'

Cities:   8%|▊         | 33/391 [00:03<00:45,  7.91it/s]

❌ 处理失败: 伊犁哈萨克州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 佛山 -> 'numpy.int64' object has no attribute 'floor'

Cities:   9%|▉         | 35/391 [00:04<00:45,  7.82it/s]

❌ 处理失败: 佳木斯 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 保定 -> 'numpy.int64' object has no attribute 'floor'

Cities:   9%|▉         | 37/391 [00:04<00:46,  7.66it/s]

❌ 处理失败: 保山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 信阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  10%|▉         | 39/391 [00:04<00:43,  8.08it/s]

❌ 处理失败: 儋州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 克孜勒苏柯尔克孜自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 克州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  11%|█         | 42/391 [00:05<00:40,  8.58it/s]

❌ 处理失败: 克拉玛依 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 六安 -> 'numpy.int64' object has no attribute 'floor'

Cities:  11%|█▏        | 44/391 [00:05<00:42,  8.13it/s]

❌ 处理失败: 六盘水 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 兰州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  12%|█▏        | 46/391 [00:05<00:41,  8.35it/s]

❌ 处理失败: 兰州新区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 兴安盟 -> 'numpy.int64' object has no attribute 'floor'

Cities:  13%|█▎        | 49/391 [00:05<00:36,  9.32it/s]

❌ 处理失败: 内江 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 凉山州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 凉山彝族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  13%|█▎        | 51/391 [00:06<00:40,  8.33it/s]

❌ 处理失败: 包头 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 北京 -> 'numpy.int64' object has no attribute 'floor'

Cities:  14%|█▎        | 53/391 [00:06<00:43,  7.79it/s]

❌ 处理失败: 北海 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 十堰 -> 'numpy.int64' object has no attribute 'floor'

Cities:  14%|█▍        | 55/391 [00:06<00:43,  7.72it/s]

❌ 处理失败: 南京 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 南充 -> 'numpy.int64' object has no attribute 'floor'

Cities:  15%|█▍        | 57/391 [00:06<00:43,  7.75it/s]

❌ 处理失败: 南宁 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 南平 -> 'numpy.int64' object has no attribute 'floor'

Cities:  15%|█▌        | 59/391 [00:07<00:43,  7.65it/s]

❌ 处理失败: 南昌 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 南通 -> 'numpy.int64' object has no attribute 'floor'

Cities:  16%|█▌        | 61/391 [00:07<00:41,  7.95it/s]

❌ 处理失败: 南阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 博尔塔拉蒙古自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 博州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  16%|█▌        | 63/391 [00:07<00:31, 10.34it/s]

❌ 处理失败: 即墨 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 厦门 -> 'numpy.int64' object has no attribute 'floor'

Cities:  17%|█▋        | 67/391 [00:07<00:33,  9.59it/s]

❌ 处理失败: 双鸭山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 句容 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 台州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  18%|█▊        | 69/391 [00:08<00:36,  8.86it/s]

❌ 处理失败: 合肥 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 吉安 -> 'numpy.int64' object has no attribute 'floor'

Cities:  18%|█▊        | 71/391 [00:08<00:38,  8.38it/s]

❌ 处理失败: 吉林 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 吐鲁番地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  19%|█▊        | 73/391 [00:08<00:39,  7.99it/s]

❌ 处理失败: 吕梁 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 吴忠 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 吴江 -> 'numpy.int64' object has no attribute 'floor'

Cities:  19%|█▉        | 76/391 [00:09<00:37,  8.42it/s]

❌ 处理失败: 周口 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 呼伦贝尔 -> 'numpy.int64' object has no attribute 'floor'

Cities:  20%|█▉        | 78/391 [00:09<00:39,  7.88it/s]

❌ 处理失败: 呼和浩特 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 和田地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  20%|██        | 80/391 [00:09<00:40,  7.70it/s]

❌ 处理失败: 咸宁 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 咸阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  21%|██        | 82/391 [00:09<00:40,  7.70it/s]

❌ 处理失败: 哈密地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 哈尔滨 -> 'numpy.int64' object has no attribute 'floor'

Cities:  21%|██▏       | 84/391 [00:10<00:40,  7.53it/s]

❌ 处理失败: 唐山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 商丘 -> 'numpy.int64' object has no attribute 'floor'

Cities:  22%|██▏       | 86/391 [00:10<00:41,  7.44it/s]

❌ 处理失败: 商洛 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 喀什地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  23%|██▎       | 88/391 [00:10<00:40,  7.51it/s]

❌ 处理失败: 嘉兴 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 嘉峪关 -> 'numpy.int64' object has no attribute 'floor'

Cities:  23%|██▎       | 90/391 [00:10<00:40,  7.51it/s]

❌ 处理失败: 四平 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 固原 -> 'numpy.int64' object has no attribute 'floor'

Cities:  24%|██▎       | 92/391 [00:11<00:40,  7.42it/s]

❌ 处理失败: 塔城地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 大兴安岭地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  24%|██▍       | 94/391 [00:11<00:41,  7.14it/s]

❌ 处理失败: 大同 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 大庆 -> 'numpy.int64' object has no attribute 'floor'

Cities:  25%|██▍       | 96/391 [00:11<00:40,  7.23it/s]

❌ 处理失败: 大理州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 大连 -> 'numpy.int64' object has no attribute 'floor'

Cities:  25%|██▌       | 98/391 [00:12<00:40,  7.27it/s]

❌ 处理失败: 天水 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 天津 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 太仓 -> 'numpy.int64' object has no attribute 'floor'

Cities:  26%|██▌       | 101/391 [00:12<00:35,  8.21it/s]

❌ 处理失败: 太原 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 威海 -> 'numpy.int64' object has no attribute 'floor'

Cities:  26%|██▋       | 103/391 [00:12<00:36,  7.90it/s]

❌ 处理失败: 娄底 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 孝感 -> 'numpy.int64' object has no attribute 'floor'

Cities:  27%|██▋       | 105/391 [00:12<00:37,  7.71it/s]

❌ 处理失败: 宁德 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宁波 -> 'numpy.int64' object has no attribute 'floor'

Cities:  27%|██▋       | 107/391 [00:13<00:37,  7.63it/s]

❌ 处理失败: 安庆 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 安康 -> 'numpy.int64' object has no attribute 'floor'

Cities:  28%|██▊       | 109/391 [00:13<00:38,  7.35it/s]

❌ 处理失败: 安阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 安顺 -> 'numpy.int64' object has no attribute 'floor'

Cities:  28%|██▊       | 110/391 [00:13<00:36,  7.60it/s]

❌ 处理失败: 定西 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宜兴 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宜宾 -> 'numpy.int64' object has no attribute 'floor'

Cities:  29%|██▉       | 114/391 [00:14<00:35,  7.88it/s]

❌ 处理失败: 宜昌 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宜春 -> 'numpy.int64' object has no attribute 'floor'

Cities:  30%|██▉       | 116/391 [00:14<00:35,  7.65it/s]

❌ 处理失败: 宝鸡 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宣城 -> 'numpy.int64' object has no attribute 'floor'

Cities:  30%|███       | 118/391 [00:14<00:36,  7.55it/s]

❌ 处理失败: 宿州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 宿迁 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 富阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  31%|███       | 121/391 [00:14<00:29,  9.16it/s]

❌ 处理失败: 寿光 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 山南 -> 'numpy.int64' object has no attribute 'floor'

Cities:  31%|███▏      | 123/391 [00:15<00:33,  8.07it/s]

❌ 处理失败: 岳阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 崇左 -> 'numpy.int64' object has no attribute 'floor'

Cities:  32%|███▏      | 125/391 [00:15<00:33,  7.99it/s]

❌ 处理失败: 巴中 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 巴彦淖尔 -> 'numpy.int64' object has no attribute 'floor'

Cities:  32%|███▏      | 127/391 [00:15<00:34,  7.75it/s]

❌ 处理失败: 巴音郭楞州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 常州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  33%|███▎      | 128/391 [00:15<00:35,  7.42it/s]

❌ 处理失败: 常德 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 常熟 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 平凉 -> 'numpy.int64' object has no attribute 'floor'

Cities:  34%|███▍      | 132/391 [00:16<00:29,  8.88it/s]

❌ 处理失败: 平度 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 平顶山 -> 'numpy.int64' object has no attribute 'floor'

Cities:  34%|███▍      | 134/391 [00:16<00:31,  8.21it/s]

❌ 处理失败: 广元 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 广安 -> 'numpy.int64' object has no attribute 'floor'

Cities:  35%|███▍      | 136/391 [00:16<00:32,  7.80it/s]

❌ 处理失败: 广州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 庆阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 库尔勒 -> 'numpy.int64' object has no attribute 'floor'

Cities:  36%|███▌      | 139/391 [00:17<00:29,  8.49it/s]

❌ 处理失败: 廊坊 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 延安 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 延边州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  36%|███▋      | 142/391 [00:17<00:27,  9.15it/s]

❌ 处理失败: 延边朝鲜族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 开封 -> 'numpy.int64' object has no attribute 'floor'

Cities:  37%|███▋      | 143/391 [00:17<00:28,  8.75it/s]

❌ 处理失败: 张家口 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 张家港 -> 'numpy.int64' object has no attribute 'floor'

Cities:  37%|███▋      | 146/391 [00:17<00:29,  8.44it/s]

❌ 处理失败: 张家界 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 张掖 -> 'numpy.int64' object has no attribute 'floor'

Cities:  38%|███▊      | 148/391 [00:18<00:30,  8.08it/s]

❌ 处理失败: 徐州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 德宏州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  38%|███▊      | 150/391 [00:18<00:31,  7.58it/s]

❌ 处理失败: 德州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 德阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  39%|███▉      | 152/391 [00:18<00:31,  7.67it/s]

❌ 处理失败: 忻州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 怀化 -> 'numpy.int64' object has no attribute 'floor'

Cities:  39%|███▉      | 154/391 [00:18<00:30,  7.75it/s]

❌ 处理失败: 怒江州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 恩施土家族苗族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 恩施州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  40%|████      | 157/391 [00:19<00:28,  8.28it/s]

❌ 处理失败: 惠州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 成都 -> 'numpy.int64' object has no attribute 'floor'

Cities:  41%|████      | 159/391 [00:19<00:29,  7.93it/s]

❌ 处理失败: 扬州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 承德 -> 'numpy.int64' object has no attribute 'floor'

Cities:  41%|████      | 161/391 [00:19<00:30,  7.45it/s]

❌ 处理失败: 抚州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 抚顺 -> 'numpy.int64' object has no attribute 'floor'

Cities:  42%|████▏     | 164/391 [00:20<00:26,  8.41it/s]

❌ 处理失败: 拉萨 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 招远 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 揭阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  42%|████▏     | 166/391 [00:20<00:27,  8.04it/s]

❌ 处理失败: 攀枝花 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 文山州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 文登 -> 'numpy.int64' object has no attribute 'floor'

Cities:  43%|████▎     | 169/391 [00:20<00:26,  8.48it/s]

❌ 处理失败: 新乡 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 新余 -> 'numpy.int64' object has no attribute 'floor'

Cities:  44%|████▎     | 171/391 [00:20<00:28,  7.80it/s]

❌ 处理失败: 无锡 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 日喀则 -> 'numpy.int64' object has no attribute 'floor'

Cities:  44%|████▍     | 172/391 [00:21<00:28,  7.74it/s]

❌ 处理失败: 日照 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 昆山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 昆明 -> 'numpy.int64' object has no attribute 'floor'

Cities:  45%|████▌     | 176/391 [00:21<00:25,  8.28it/s]

❌ 处理失败: 昌吉州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 昌都 -> 'numpy.int64' object has no attribute 'floor'

Cities:  46%|████▌     | 178/391 [00:21<00:26,  7.90it/s]

❌ 处理失败: 昭通 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 晋中 -> 'numpy.int64' object has no attribute 'floor'

Cities:  46%|████▌     | 180/391 [00:22<00:27,  7.56it/s]

❌ 处理失败: 晋城 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 普洱 -> 'numpy.int64' object has no attribute 'floor'

Cities:  47%|████▋     | 182/391 [00:22<00:27,  7.63it/s]

❌ 处理失败: 景德镇 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 曲靖 -> 'numpy.int64' object has no attribute 'floor'

Cities:  47%|████▋     | 184/391 [00:22<00:27,  7.45it/s]

❌ 处理失败: 朔州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 朝阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  48%|████▊     | 186/391 [00:22<00:27,  7.51it/s]

❌ 处理失败: 本溪 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 来宾 -> 'numpy.int64' object has no attribute 'floor'

Cities:  48%|████▊     | 188/391 [00:23<00:26,  7.53it/s]

❌ 处理失败: 杭州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 松原 -> 'numpy.int64' object has no attribute 'floor'

Cities:  49%|████▉     | 191/391 [00:23<00:22,  9.08it/s]

❌ 处理失败: 林芝 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 果洛州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 果洛藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  49%|████▉     | 193/391 [00:23<00:23,  8.32it/s]

❌ 处理失败: 枣庄 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 柳州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  50%|████▉     | 195/391 [00:24<00:24,  8.02it/s]

❌ 处理失败: 株洲 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 桂林 -> 'numpy.int64' object has no attribute 'floor'

Cities:  50%|█████     | 197/391 [00:24<00:25,  7.74it/s]

❌ 处理失败: 梅州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 梧州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  51%|█████     | 199/391 [00:24<00:24,  7.82it/s]

❌ 处理失败: 楚雄州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 榆林 -> 'numpy.int64' object has no attribute 'floor'

Cities:  51%|█████▏    | 201/391 [00:24<00:25,  7.49it/s]

❌ 处理失败: 武威 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 武汉 -> 'numpy.int64' object has no attribute 'floor'

Cities:  52%|█████▏    | 203/391 [00:25<00:25,  7.48it/s]

❌ 处理失败: 毕节 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 永州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  52%|█████▏    | 205/391 [00:25<00:24,  7.45it/s]

❌ 处理失败: 汉中 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 汕头 -> 'numpy.int64' object has no attribute 'floor'

Cities:  53%|█████▎    | 207/391 [00:25<00:24,  7.48it/s]

❌ 处理失败: 汕尾 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 江门 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 江阴 -> 'numpy.int64' object has no attribute 'floor'

Cities:  54%|█████▎    | 210/391 [00:25<00:22,  8.16it/s]

❌ 处理失败: 池州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 沈阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  54%|█████▍    | 212/391 [00:26<00:23,  7.77it/s]

❌ 处理失败: 沧州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 河池 -> 'numpy.int64' object has no attribute 'floor'

Cities:  55%|█████▍    | 214/391 [00:26<00:22,  7.77it/s]

❌ 处理失败: 河源 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 泉州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  55%|█████▌    | 216/391 [00:26<00:23,  7.61it/s]

❌ 处理失败: 泰安 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 泰州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  56%|█████▌    | 218/391 [00:26<00:22,  7.73it/s]

❌ 处理失败: 泸州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 洛阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  56%|█████▋    | 220/391 [00:27<00:21,  7.88it/s]

❌ 处理失败: 济南 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 济宁 -> 'numpy.int64' object has no attribute 'floor'

Cities:  57%|█████▋    | 223/391 [00:27<00:18,  9.17it/s]

❌ 处理失败: 海东地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 海北州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 海北藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  58%|█████▊    | 225/391 [00:27<00:17,  9.38it/s]

❌ 处理失败: 海南州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 海南藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  58%|█████▊    | 228/391 [00:28<00:17,  9.49it/s]

❌ 处理失败: 海口 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 海西州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 海西蒙古族藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  59%|█████▉    | 230/391 [00:28<00:16,  9.52it/s]

❌ 处理失败: 海门 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 淄博 -> 'numpy.int64' object has no attribute 'floor'

Cities:  59%|█████▉    | 232/391 [00:28<00:18,  8.73it/s]

❌ 处理失败: 淮北 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 淮南 -> 'numpy.int64' object has no attribute 'floor'

Cities:  60%|█████▉    | 234/391 [00:28<00:18,  8.39it/s]

❌ 处理失败: 淮安 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 深圳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  60%|██████    | 236/391 [00:29<00:19,  8.09it/s]

❌ 处理失败: 清远 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 温州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  61%|██████    | 238/391 [00:29<00:19,  7.94it/s]

❌ 处理失败: 渭南 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 湖州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  61%|██████▏   | 240/391 [00:29<00:19,  7.81it/s]

❌ 处理失败: 湘潭 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 湘西州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  62%|██████▏   | 241/391 [00:29<00:19,  7.82it/s]

❌ 处理失败: 湛江 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 溧阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 滁州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  63%|██████▎   | 245/391 [00:30<00:18,  7.99it/s]

❌ 处理失败: 滨州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 漯河 -> 'numpy.int64' object has no attribute 'floor'

Cities:  63%|██████▎   | 247/391 [00:30<00:18,  7.82it/s]

❌ 处理失败: 漳州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 潍坊 -> 'numpy.int64' object has no attribute 'floor'

Cities:  64%|██████▎   | 249/391 [00:30<00:18,  7.84it/s]

❌ 处理失败: 潮州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 濮阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  64%|██████▍   | 251/391 [00:30<00:17,  7.80it/s]

❌ 处理失败: 烟台 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 焦作 -> 'numpy.int64' object has no attribute 'floor'

Cities:  65%|██████▍   | 253/391 [00:31<00:17,  7.71it/s]

❌ 处理失败: 牡丹江 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 玉林 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 玉树州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  65%|██████▌   | 256/391 [00:31<00:15,  8.70it/s]

❌ 处理失败: 玉树藏族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 玉溪 -> 'numpy.int64' object has no attribute 'floor'

Cities:  66%|██████▌   | 259/391 [00:31<00:13,  9.59it/s]

❌ 处理失败: 珠海 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 瓦房店 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 甘南州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  67%|██████▋   | 261/391 [00:31<00:12, 10.28it/s]

❌ 处理失败: 甘孜州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 甘孜藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  67%|██████▋   | 263/391 [00:32<00:14,  9.01it/s]

❌ 处理失败: 白城 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 白山 -> 'numpy.int64' object has no attribute 'floor'

Cities:  68%|██████▊   | 265/391 [00:32<00:15,  8.30it/s]

❌ 处理失败: 白银 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 百色 -> 'numpy.int64' object has no attribute 'floor'

Cities:  68%|██████▊   | 267/391 [00:32<00:15,  8.15it/s]

❌ 处理失败: 益阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 盐城 -> 'numpy.int64' object has no attribute 'floor'

Cities:  69%|██████▉   | 269/391 [00:33<00:15,  7.92it/s]

❌ 处理失败: 盘锦 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 眉山 -> 'numpy.int64' object has no attribute 'floor'

Cities:  69%|██████▉   | 271/391 [00:33<00:15,  7.87it/s]

❌ 处理失败: 石嘴山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 石家庄 -> 'numpy.int64' object has no attribute 'floor'

Cities:  70%|██████▉   | 273/391 [00:33<00:15,  7.71it/s]

❌ 处理失败: 石河子 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 福州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  70%|███████   | 274/391 [00:33<00:15,  7.57it/s]

❌ 处理失败: 秦皇岛 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 章丘 -> 'numpy.int64' object has no attribute 'floor'

Cities:  71%|███████   | 277/391 [00:34<00:13,  8.20it/s]

❌ 处理失败: 红河州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 绍兴 -> 'numpy.int64' object has no attribute 'floor'

Cities:  71%|███████▏  | 279/391 [00:34<00:14,  7.89it/s]

❌ 处理失败: 绥化 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 绵阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  72%|███████▏  | 281/391 [00:34<00:14,  7.71it/s]

❌ 处理失败: 聊城 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 肇庆 -> 'numpy.int64' object has no attribute 'floor'

Cities:  72%|███████▏  | 283/391 [00:34<00:11,  9.75it/s]

❌ 处理失败: 胶南 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 胶州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 自贡 -> 'numpy.int64' object has no attribute 'floor'

Cities:  73%|███████▎  | 286/391 [00:35<00:12,  8.34it/s]

❌ 处理失败: 舟山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 芜湖 -> 'numpy.int64' object has no attribute 'floor'

Cities:  74%|███████▎  | 288/391 [00:35<00:12,  8.03it/s]

❌ 处理失败: 苏州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 茂名 -> 'numpy.int64' object has no attribute 'floor'

Cities:  74%|███████▍  | 290/391 [00:35<00:12,  7.82it/s]

❌ 处理失败: 荆州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 荆门 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 荣成 -> 'numpy.int64' object has no attribute 'floor'

Cities:  75%|███████▌  | 294/391 [00:35<00:09, 10.45it/s]

❌ 处理失败: 莆田 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 莱州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 莱西 -> 'numpy.int64' object has no attribute 'floor'

Cities:  76%|███████▌  | 296/391 [00:36<00:10,  9.24it/s]

❌ 处理失败: 菏泽 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 萍乡 -> 'numpy.int64' object has no attribute 'floor'

Cities:  76%|███████▌  | 298/391 [00:36<00:10,  8.67it/s]

❌ 处理失败: 营口 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 葫芦岛 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 蓬莱 -> 'numpy.int64' object has no attribute 'floor'

Cities:  77%|███████▋  | 301/391 [00:36<00:09,  9.09it/s]

❌ 处理失败: 蚌埠 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 衡水 -> 'numpy.int64' object has no attribute 'floor'

Cities:  77%|███████▋  | 303/391 [00:37<00:10,  8.55it/s]

❌ 处理失败: 衡阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 衢州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  78%|███████▊  | 305/391 [00:37<00:10,  8.27it/s]

❌ 处理失败: 襄阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 西双版纳州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  79%|███████▊  | 307/391 [00:37<00:09,  8.43it/s]

❌ 处理失败: 西咸新区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 西宁 -> 'numpy.int64' object has no attribute 'floor'

Cities:  79%|███████▉  | 309/391 [00:37<00:10,  8.07it/s]

❌ 处理失败: 西安 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 许昌 -> 'numpy.int64' object has no attribute 'floor'

Cities:  80%|███████▉  | 311/391 [00:37<00:09,  8.71it/s]

❌ 处理失败: 诸暨 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 贵港 -> 'numpy.int64' object has no attribute 'floor'

Cities:  80%|████████  | 313/391 [00:38<00:09,  8.26it/s]

❌ 处理失败: 贵阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 贺州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  81%|████████  | 315/391 [00:38<00:09,  8.07it/s]

❌ 处理失败: 资阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 赣州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  81%|████████  | 317/391 [00:38<00:08,  8.25it/s]

❌ 处理失败: 赣江新区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 赤峰 -> 'numpy.int64' object has no attribute 'floor'

Cities:  82%|████████▏ | 319/391 [00:38<00:08,  8.06it/s]

❌ 处理失败: 辽源 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 辽阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  82%|████████▏ | 321/391 [00:39<00:08,  7.93it/s]

❌ 处理失败: 达州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 运城 -> 'numpy.int64' object has no attribute 'floor'

Cities:  83%|████████▎ | 323/391 [00:39<00:08,  7.62it/s]

❌ 处理失败: 连云港 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 迪庆州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  83%|████████▎ | 325/391 [00:39<00:08,  7.59it/s]

❌ 处理失败: 通化 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 通辽 -> 'numpy.int64' object has no attribute 'floor'

Cities:  84%|████████▎ | 327/391 [00:40<00:08,  7.56it/s]

❌ 处理失败: 遂宁 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 遵义 -> 'numpy.int64' object has no attribute 'floor'

Cities:  84%|████████▍ | 330/391 [00:40<00:06,  9.03it/s]

❌ 处理失败: 邢台 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 那曲 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 那曲地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  85%|████████▍ | 332/391 [00:40<00:06,  8.60it/s]

❌ 处理失败: 邯郸 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 邵阳 -> 'numpy.int64' object has no attribute 'floor'

Cities:  85%|████████▌ | 334/391 [00:40<00:06,  8.21it/s]

❌ 处理失败: 郑州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 郴州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  86%|████████▌ | 336/391 [00:41<00:06,  7.97it/s]

❌ 处理失败: 鄂尔多斯 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 鄂州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  86%|████████▋ | 338/391 [00:41<00:06,  8.07it/s]

❌ 处理失败: 酒泉 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 重庆 -> 'numpy.int64' object has no attribute 'floor'

Cities:  87%|████████▋ | 339/391 [00:41<00:06,  7.75it/s]

❌ 处理失败: 金华 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 金坛 -> 'numpy.int64' object has no attribute 'floor'

Cities:  87%|████████▋ | 342/391 [00:41<00:05,  8.25it/s]

❌ 处理失败: 金昌 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 钦州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  88%|████████▊ | 344/391 [00:42<00:05,  8.07it/s]

❌ 处理失败: 铁岭 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 铜仁地区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  88%|████████▊ | 346/391 [00:42<00:05,  7.74it/s]

❌ 处理失败: 铜川 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 铜陵 -> 'numpy.int64' object has no attribute 'floor'

Cities:  89%|████████▉ | 348/391 [00:42<00:05,  7.60it/s]

❌ 处理失败: 银川 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 锡林郭勒盟 -> 'numpy.int64' object has no attribute 'floor'

Cities:  90%|████████▉ | 350/391 [00:42<00:05,  7.73it/s]

❌ 处理失败: 锦州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 镇江 -> 'numpy.int64' object has no attribute 'floor'

Cities:  90%|█████████ | 352/391 [00:43<00:05,  7.76it/s]

❌ 处理失败: 长春 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 长沙 -> 'numpy.int64' object has no attribute 'floor'

Cities:  91%|█████████ | 354/391 [00:43<00:05,  7.39it/s]

❌ 处理失败: 长治 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 阜新 -> 'numpy.int64' object has no attribute 'floor'

Cities:  91%|█████████ | 356/391 [00:43<00:04,  7.48it/s]

❌ 处理失败: 阜阳 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 防城港 -> 'numpy.int64' object has no attribute 'floor'

Cities:  92%|█████████▏| 358/391 [00:43<00:04,  7.46it/s]

❌ 处理失败: 阳江 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 阳泉 -> 'numpy.int64' object has no attribute 'floor'

Cities:  92%|█████████▏| 360/391 [00:44<00:04,  7.52it/s]

❌ 处理失败: 阿克苏地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 阿勒泰地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 阿坝州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  93%|█████████▎| 363/391 [00:44<00:03,  8.71it/s]

❌ 处理失败: 阿坝藏族羌族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 阿拉善盟 -> 'numpy.int64' object has no attribute 'floor'

Cities:  93%|█████████▎| 365/391 [00:44<00:03,  8.31it/s]

❌ 处理失败: 阿里地区 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 陇南 -> 'numpy.int64' object has no attribute 'floor'

Cities:  94%|█████████▍| 367/391 [00:44<00:02,  8.28it/s]

❌ 处理失败: 随州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 雄安新区 -> 'numpy.int64' object has no attribute 'floor'

Cities:  94%|█████████▍| 369/391 [00:45<00:02,  7.47it/s]

❌ 处理失败: 雅安 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 青岛 -> 'numpy.int64' object has no attribute 'floor'

Cities:  95%|█████████▍| 371/391 [00:45<00:02,  7.52it/s]

❌ 处理失败: 鞍山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 韶关 -> 'numpy.int64' object has no attribute 'floor'

Cities:  95%|█████████▌| 373/391 [00:45<00:02,  7.52it/s]

❌ 处理失败: 马鞍山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 驻马店 -> 'numpy.int64' object has no attribute 'floor'

Cities:  96%|█████████▌| 375/391 [00:46<00:02,  7.26it/s]

❌ 处理失败: 鸡西 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 鹤壁 -> 'numpy.int64' object has no attribute 'floor'

Cities:  96%|█████████▋| 377/391 [00:46<00:02,  6.78it/s]

❌ 处理失败: 鹤岗 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 鹰潭 -> 'numpy.int64' object has no attribute 'floor'

Cities:  97%|█████████▋| 380/391 [00:46<00:01,  8.13it/s]

❌ 处理失败: 黄冈 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黄南州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黄南藏族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  98%|█████████▊| 382/391 [00:47<00:01,  7.30it/s]

❌ 处理失败: 黄山 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黄石 -> 'numpy.int64' object has no attribute 'floor'

Cities:  98%|█████████▊| 383/391 [00:47<00:01,  7.04it/s]

❌ 处理失败: 黑河 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黔东南州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黔东南苗族侗族自治州 -> 'numpy.int64' object has no attribute 'floor'

Cities:  99%|█████████▉| 387/391 [00:47<00:00,  8.90it/s]

❌ 处理失败: 黔南州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黔南布依族苗族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 黔西南州 -> 'numpy.int64' object has no attribute 'floor'

Cities: 100%|█████████▉| 390/391 [00:47<00:00,  8.95it/s]

❌ 处理失败: 黔西南布依族苗族自治州 -> 'numpy.int64' object has no attribute 'floor'
❌ 处理失败: 齐齐哈尔 -> 'numpy.int64' object has no attribute 'floor'

Cities: 100%|██████████| 391/391 [00:48<00:00,  8.14it/s]

❌ 处理失败: 龙岩 -> 'numpy.int64' object has no attribute 'floor'
全部完成。cleaned files at: D:\Downloads\FYP CHINA\data\cleaned_cities
master file: D:\Downloads\FYP CHINA\data\cleaned_all_cities.csv
summary: D:\Downloads\FYP CHINA\data\clean_summary.csv

In [5]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

input_path = r"D:\Downloads\FYP CHINA\data\cities"
output_path = r"D:\Downloads\FYP CHINA\data\cleaned_cities"

os.makedirs(output_path, exist_ok=True)

city_files = glob.glob(os.path.join(input_path, "*.csv"))

for file in tqdm(city_files, desc="Cities"):

    city = os.path.basename(file).replace(".csv", "")

    try:
        df = pd.read_csv(file, encoding="utf-8")

        # 删除重复
        df = df.drop_duplicates()

        # 转换日期
        df["date"] = pd.to_datetime(df["date"], errors="coerce")

        # 空值处理：污染物为空 → 填为 NaN，不做 floor
        pollutants = ["AQI","PM2.5","PM10","SO2","NO2","CO","O3"]
        for col in pollutants:
            if col in df.columns:
                # 转成 float，再 floor，再转 int，避免报错
                df[col] = pd.to_numeric(df[col], errors="coerce")
                df[col] = np.floor(df[col].astype(float))

        # 保存文件
        df.to_csv(
            os.path.join(output_path, f"{city}.csv"),
            index=False,
            encoding="utf-8"
        )

    except Exception as e:
        print(f"❌ 处理失败: {city} -> {e}")

Cities: 100%|██████████| 391/391 [01:42<00:00,  3.82it/s]

In [6]:
import os
import pandas as pd
from tqdm import tqdm

root = r"D:\Downloads\FYP CHINA\data"
input_dir = os.path.join(root, "cleaned_cities")
output_dir = os.path.join(root, "daily_cities")

os.makedirs(output_dir, exist_ok=True)

# 自动识别污染物列（你不需要手动列）
def detect_pollutant_columns(df):
    exclude = {"city", "date", "hour"}
    return [col for col in df.columns if col not in exclude]

files = [f for f in os.listdir(input_dir) if f.endswith(".csv")]

print("Daily 生成开始，共有城市：", len(files))

for file in tqdm(files):
    path = os.path.join(input_dir, file)
    df = pd.read_csv(path, encoding="utf-8")

    # 日期格式标准化
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    # 找出所有污染物列
    pollutant_cols = detect_pollutant_columns(df)

    # 按天聚合（平均值）
    daily = (
        df.groupby("date")[pollutant_cols]
        .mean(numeric_only=True)
        .reset_index()
    )

    # 加回 city 字段
    city_name = file.replace(".csv", "")
    daily.insert(0, "city", city_name)

    # 保存
    daily_file = os.path.join(output_dir, f"{city_name}_daily.csv")
    daily.to_csv(daily_file, index=False, encoding="utf-8")

print("\n全部城市 Daily 数据生成完毕！")
print("输出位置：", output_dir)

Daily 生成开始，共有城市： 391

100%|██████████| 391/391 [00:24<00:00, 16.22it/s]

全部城市 Daily 数据生成完毕！
输出位置： D:\Downloads\FYP CHINA\data\daily_cities

In [7]:
#read csv 
import pandas as pd
df = pd.read_csv("./data/daily_cities/北京_daily.csv", encoding="utf-8")
df.head(5)

,city,date,AQI,CO,NO2,O3,PM10,PM2.5,SO2
0,北京,2020-01-01,51.958333,0.041667,48.875000,10.291667,55.000000,33.708333,6.708333
1,北京,2020-01-02,70.375000,0.958333,62.541667,8.875000,78.916667,50.875000,7.333333
2,北京,2020-01-03,70.250000,0.708333,63.666667,13.875000,72.041667,50.500000,7.916667
3,北京,2020-01-04,60.750000,0.625000,58.583333,20.500000,66.000000,42.166667,7.125000
4,北京,2020-01-05,86.041667,1.000000,65.833333,7.208333,79.166667,63.708333,7.166667

In [1]:
import pandas as pd
import os
from tqdm import tqdm

CLEANED_DIR = r"D:\Downloads\FYP CHINA\data\cleaned_cities"
DAILY_DIR = r"D:\Downloads\FYP CHINA\data\daily_cities"
OUTPUT = r"D:\Downloads\FYP CHINA\data\master_daily.csv"

def load_folder(path):
    dfs = []
    files = [f for f in os.listdir(path) if f.endswith(".csv")]
    for f in tqdm(files, desc=f"Loading {path}"):
        fp = os.path.join(path, f)
        try:
            df = pd.read_csv(fp)
            # 标准化字段
            if "date" in df.columns:
                df["date"] = pd.to_datetime(df["date"], errors="coerce")
            dfs.append(df)
        except Exception as e:
            print("❌ Error:", fp, e)
    return dfs


print("📦 Loading cleaned cities...")
cleaned = load_folder(CLEANED_DIR)

print("📦 Loading daily cities...")
daily = load_folder(DAILY_DIR)

print("🔗 Merging...")
all_df = cleaned + daily

df = pd.concat(all_df, ignore_index=True)

print("🧹 Cleaning & Sorting...")
df = df.drop_duplicates()
df = df.dropna(subset=["city", "date"])
df = df.sort_values(["city", "date", "hour"])

print("💾 Saving to master_daily.csv...")
df.to_csv(OUTPUT, index=False, encoding="utf-8-sig")

print("🎉 Done!")
print("⚡ master_daily.csv 已生成，共记录:", len(df))

📦 Loading cleaned cities...

Loading D:\Downloads\FYP CHINA\data\cleaned_cities: 100%|██████████| 391/391 [00:22<00:00, 17.45it/s]

📦 Loading daily cities...

Loading D:\Downloads\FYP CHINA\data\daily_cities: 100%|██████████| 391/391 [00:09<00:00, 43.08it/s]

🔗 Merging...
🧹 Cleaning & Sorting...
💾 Saving to master_daily.csv...
🎉 Done!
⚡ master_daily.csv 已生成，共记录: 18066626

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("./data/master_daily.csv")
df["date"] = pd.to_datetime(df["date"])

df.head(5)

        date  hour city   AQI   CO   NO2    O3  PM10  PM2.5   SO2
0 2020-01-01   0.0  七台河  63.0  0.0  44.0  29.0  58.0   45.0  17.0
1 2020-01-01   1.0  七台河  70.0  0.0  39.0  33.0  56.0   51.0  21.0
2 2020-01-01   2.0  七台河  74.0  0.0  47.0  27.0  63.0   54.0  18.0
3 2020-01-01   3.0  七台河  66.0  0.0  37.0  39.0  56.0   48.0  15.0
4 2020-01-01   4.0  七台河  60.0  0.0  34.0  36.0  58.0   43.0  17.0